package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduResourcePO;
import java.util.List;

public interface AieduResourcePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_resource
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_resource
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    int insert(AieduResourcePO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_resource
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    AieduResourcePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_resource
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    List<AieduResourcePO> selectAll(AieduResourcePO po);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_resource
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    int updateByPrimaryKey(AieduResourcePO row);
}
