package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduClassPO;
import java.util.List;

public interface AieduClassPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_class
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    int deleteByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_class
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    int insert(AieduClassPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_class
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    AieduClassPO selectByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_class
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    List<AieduClassPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_class
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    int updateByPrimaryKey(AieduClassPO row);

    int updateStudentCount(Integer classId);
}
