package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduSolutionPO;
import java.util.List;

public interface AieduSolutionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_solution
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_solution
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    int insert(AieduSolutionPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_solution
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    AieduSolutionPO selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_solution
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    List<AieduSolutionPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_solution
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    int updateByPrimaryKey(AieduSolutionPO row);
}