package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduStudentPO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AieduStudentPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_student
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_student
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    int insert(AieduStudentPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_student
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    AieduStudentPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_student
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    List<AieduStudentPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_student
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    int updateByPrimaryKey(AieduStudentPO row);

    List<AieduStudentPO> selectListByStudentIdAndClassId(@Param("studentId") String studentId,
                                                         @Param("classId") Integer classId);

    List<AieduStudentPO> selectList(@Param("classId") Integer classId,
                                    @Param("search") String search);

    int deleteByClassId(Integer classId);
}
