package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduLiteracyClassPO;
import java.util.List;

public interface AieduLiteracyClassPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_literacy_class
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_literacy_class
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    int insert(AieduLiteracyClassPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_literacy_class
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    AieduLiteracyClassPO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_literacy_class
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    List<AieduLiteracyClassPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_literacy_class
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    int updateByPrimaryKey(AieduLiteracyClassPO row);
}