package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduHomeConfigPO;
import java.util.List;

public interface AieduHomeConfigPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_home_config
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_home_config
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    int insert(AieduHomeConfigPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_home_config
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    AieduHomeConfigPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_home_config
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    List<AieduHomeConfigPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_home_config
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    int updateByPrimaryKey(AieduHomeConfigPO row);
}