package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduInquiryPO;
import java.util.List;

public interface AieduInquiryPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_inquiry
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_inquiry
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    int insert(AieduInquiryPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_inquiry
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    AieduInquiryPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_inquiry
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    List<AieduInquiryPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_inquiry
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    int updateByPrimaryKey(AieduInquiryPO row);
}