package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduTeachersPO;
import java.util.List;

public interface AieduTeachersPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_teachers
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_teachers
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    int insert(AieduTeachersPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_teachers
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    AieduTeachersPO selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_teachers
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    List<AieduTeachersPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_teachers
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    int updateByPrimaryKey(AieduTeachersPO row);

    AieduTeachersPO selectByUserId(Long userId);

    int updateByUserId(AieduTeachersPO po);
}
