package com.braight.dc.admin.web.mapper;

import com.braight.dc.admin.web.entity.AieduClassroomsPO;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface AieduClassroomsPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_classrooms
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_classrooms
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    int insert(AieduClassroomsPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_classrooms
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    AieduClassroomsPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_classrooms
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    List<AieduClassroomsPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aiedu_classrooms
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    int updateByPrimaryKey(AieduClassroomsPO row);

    List<AieduClassroomsPO> selectListFeatured();

    int updateLastUsedAt(@Param("classroomId") Integer classroomId,
                         @Param("lastUsedAt") Date lastUsedAt);
}
