package com.braight.dc.admin.web.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.validation.constraints.Size;
import java.util.Date;

public class AieduClassPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_class.class_id
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    private Integer teacherId;
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_class.grade
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_class.class_name
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    private String className;
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_class.student_count
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    private Integer studentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_class.created_at
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_class.updated_at
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updatedAt;

    public Integer getTeacherId() {
        return teacherId;
    }

    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    @Size(max = 1000, message = "描述长度不能超过1000")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_class.class_id
     *
     * @return the value of aiedu_class.class_id
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_class.class_id
     *
     * @param classId the value for aiedu_class.class_id
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_class.grade
     *
     * @return the value of aiedu_class.grade
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    @Size(min = 1, max = 20, message = "年级长度不能超过20")
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_class.grade
     *
     * @param grade the value for aiedu_class.grade
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_class.class_name
     *
     * @return the value of aiedu_class.class_name
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    @Size(min = 1, max = 50, message = "班级名称长度不能超过50")
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_class.class_name
     *
     * @param className the value for aiedu_class.class_name
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_class.student_count
     *
     * @return the value of aiedu_class.student_count
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public Integer getStudentCount() {
        return studentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_class.student_count
     *
     * @param studentCount the value for aiedu_class.student_count
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public void setStudentCount(Integer studentCount) {
        this.studentCount = studentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_class.created_at
     *
     * @return the value of aiedu_class.created_at
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_class.created_at
     *
     * @param createdAt the value for aiedu_class.created_at
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_class.updated_at
     *
     * @return the value of aiedu_class.updated_at
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_class.updated_at
     *
     * @param updatedAt the value for aiedu_class.updated_at
     *
     * @mbg.generated Tue Jan 13 09:27:20 GMT+08:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}
