package com.braight.dc.admin.web.entity;

import com.alibaba.fastjson2.JSONObject;
import lombok.Data;
import org.springframework.data.annotation.Transient;

@Data
public class AieduHomeConfigPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_home_config.id
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_home_config.content_json
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    private String contentJson;
    @Transient
    private JSONObject homeConfig;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_home_config.id
     *
     * @return the value of aiedu_home_config.id
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_home_config.id
     *
     * @param id the value for aiedu_home_config.id
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_home_config.content_json
     *
     * @return the value of aiedu_home_config.content_json
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    public String getContentJson() {
        return contentJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_home_config.content_json
     *
     * @param contentJson the value for aiedu_home_config.content_json
     *
     * @mbg.generated Tue Dec 30 16:09:24 GMT+08:00 2025
     */
    public void setContentJson(String contentJson) {
        this.contentJson = contentJson;
    }

    public JSONObject getHomeConfig() {
        return this.homeConfig;
    }

    public void setHomeConfig(JSONObject homeConfig) {
        this.homeConfig = homeConfig;
    }
}
