package com.braight.dc.admin.web.entity;

import com.alibaba.fastjson2.JSONObject;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;

@Data
public class AieduClassroomsPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.id
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    private Integer classroomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.teacher_id
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.name
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    @Size(min = 1, max = 200, message = "课堂名称长度不能超过200个字符")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.grade
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    @Size(min = 1, max = 20, message = "年级长度不能超过50个字符")
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.class_name
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    @Size(max = 50, message = "班级长度不能超过50个字符")
    private String className;

    private Boolean featured = false;

    public Boolean getFeatured() {
        return featured;
    }

    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.created_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.updated_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.last_used_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date lastUsedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.ai_tool_json
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    private String aiToolJson;
    @NotNull(message = "请选择 AI 工具")
    private JSONObject aiTool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.courseware_json
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    private String coursewareJson;
    @NotNull(message = "请选择课件")
    private JSONObject courseware;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_classrooms.quiz_config_json
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    private String quizConfigJson;
    private JSONObject quizConfig;
    private Boolean isTemplate = false;

    public JSONObject getAiTool() {
        return aiTool;
    }

    public void setAiTool(JSONObject aiTool) {
        this.aiTool = aiTool;
    }

    public JSONObject getCourseware() {
        return courseware;
    }

    public void setCourseware(JSONObject courseware) {
        this.courseware = courseware;
    }

    public JSONObject getQuizConfig() {
        return quizConfig;
    }

    public void setQuizConfig(JSONObject quizConfig) {
        this.quizConfig = quizConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_classrooms.id
     *
     * @return the value of aiedu_classrooms.id
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public Integer getClassroomId() {
        return classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_classrooms.id
     *
     * @param classroomId the value for aiedu_classrooms.id
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public void setClassroomId(Integer classroomId) {
        this.classroomId = classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_classrooms.teacher_id
     *
     * @return the value of aiedu_classrooms.teacher_id
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_classrooms.teacher_id
     *
     * @param teacherId the value for aiedu_classrooms.teacher_id
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_classrooms.name
     *
     * @return the value of aiedu_classrooms.name
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_classrooms.name
     *
     * @param name the value for aiedu_classrooms.name
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_classrooms.grade
     *
     * @return the value of aiedu_classrooms.grade
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_classrooms.grade
     *
     * @param grade the value for aiedu_classrooms.grade
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_classrooms.class_name
     *
     * @return the value of aiedu_classrooms.class_name
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_classrooms.class_name
     *
     * @param className the value for aiedu_classrooms.class_name
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_classrooms.created_at
     *
     * @return the value of aiedu_classrooms.created_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_classrooms.created_at
     *
     * @param createdAt the value for aiedu_classrooms.created_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_classrooms.updated_at
     *
     * @return the value of aiedu_classrooms.updated_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_classrooms.updated_at
     *
     * @param updatedAt the value for aiedu_classrooms.updated_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_classrooms.last_used_at
     *
     * @return the value of aiedu_classrooms.last_used_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public Date getLastUsedAt() {
        return lastUsedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_classrooms.last_used_at
     *
     * @param lastUsedAt the value for aiedu_classrooms.last_used_at
     *
     * @mbg.generated Tue Jan 13 17:29:07 GMT+08:00 2026
     */
    public void setLastUsedAt(Date lastUsedAt) {
        this.lastUsedAt = lastUsedAt;
    }

}
