package com.braight.dc.admin.web.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.data.annotation.Transient;

import javax.validation.constraints.NotBlank;
import java.util.Date;

@Data
public class AieduResourcePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.id
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.type
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.title
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.title_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String titleEn;
    @Transient
    private String titleOrTitleEn; // 查询条件

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.cover_image
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String coverImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.tag
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String tag;
    @Transient
    private String[] tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.tag_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String tagEn;

    @Transient
    private String[] tagEns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.featured
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private Boolean featured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.created_time
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.updated_time
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updatedAt;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.link_type
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String linkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.link_url
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.author
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.duration
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.grade
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.summary
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.summary_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String summaryEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_resource.content
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.id
     *
     * @return the value of aiedu_resource.id
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.id
     *
     * @param id the value for aiedu_resource.id
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    @NotBlank(message = "资源类型不能为空")
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.type
     *
     * @return the value of aiedu_resource.type
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.type
     *
     * @param type the value for aiedu_resource.type
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setType(String type) {
        this.type = type;
    }

    @NotBlank(message = "资源中文标题不能为空")
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.title
     *
     * @return the value of aiedu_resource.title
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.title
     *
     * @param title the value for aiedu_resource.title
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    @NotBlank(message = "资源英文标题不能为空")
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.title_en
     *
     * @return the value of aiedu_resource.title_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getTitleEn() {
        return titleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.title_en
     *
     * @param titleEn the value for aiedu_resource.title_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setTitleEn(String titleEn) {
        this.titleEn = titleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.cover_image
     *
     * @return the value of aiedu_resource.cover_image
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.cover_image
     *
     * @param coverImage the value for aiedu_resource.cover_image
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.tag
     *
     * @return the value of aiedu_resource.tag
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.tag
     *
     * @param tag the value for aiedu_resource.tag
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.tag_en
     *
     * @return the value of aiedu_resource.tag_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getTagEn() {
        return tagEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.tag_en
     *
     * @param tagEn the value for aiedu_resource.tag_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setTagEn(String tagEn) {
        this.tagEn = tagEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.featured
     *
     * @return the value of aiedu_resource.featured
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public Boolean getFeatured() {
        return featured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.featured
     *
     * @param featured the value for aiedu_resource.featured
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.link_type
     *
     * @return the value of aiedu_resource.link_type
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.link_type
     *
     * @param linkType the value for aiedu_resource.link_type
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setLinkType(String linkType) {
        this.linkType = linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.link_url
     *
     * @return the value of aiedu_resource.link_url
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.link_url
     *
     * @param linkUrl the value for aiedu_resource.link_url
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.author
     *
     * @return the value of aiedu_resource.author
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.author
     *
     * @param author the value for aiedu_resource.author
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.duration
     *
     * @return the value of aiedu_resource.duration
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.duration
     *
     * @param duration the value for aiedu_resource.duration
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.grade
     *
     * @return the value of aiedu_resource.grade
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.grade
     *
     * @param grade the value for aiedu_resource.grade
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.summary
     *
     * @return the value of aiedu_resource.summary
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.summary
     *
     * @param summary the value for aiedu_resource.summary
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.summary_en
     *
     * @return the value of aiedu_resource.summary_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getSummaryEn() {
        return summaryEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.summary_en
     *
     * @param summaryEn the value for aiedu_resource.summary_en
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setSummaryEn(String summaryEn) {
        this.summaryEn = summaryEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_resource.content
     *
     * @return the value of aiedu_resource.content
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_resource.content
     *
     * @param content the value for aiedu_resource.content
     *
     * @mbg.generated Wed Dec 31 10:33:51 GMT+08:00 2025
     */
    public void setContent(String content) {
        this.content = content;
    }
}
