package com.braight.dc.admin.web.entity;

import com.alibaba.excel.annotation.ExcelIgnore;
import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.write.style.ColumnWidth;
import lombok.Data;

import java.util.Date;

@Data
@ColumnWidth(20)
public class AieduStudentPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_student.id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    @ExcelIgnore
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_student.class_id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    @ExcelIgnore
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_student.student_id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    @ExcelProperty(value = "学号", index = 0)
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_student.name
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    @ExcelProperty(value = "姓名", index = 1)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_student.gender
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    @ExcelProperty(value = "性别", index = 2)
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_student.created_at
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    @ExcelIgnore
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_student.updated_at
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    @ExcelIgnore
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_student.remark
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    @ExcelProperty(value = "备注", index = 3)
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_student.id
     *
     * @return the value of aiedu_student.id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_student.id
     *
     * @param id the value for aiedu_student.id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_student.class_id
     *
     * @return the value of aiedu_student.class_id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_student.class_id
     *
     * @param classId the value for aiedu_student.class_id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_student.student_id
     *
     * @return the value of aiedu_student.student_id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_student.student_id
     *
     * @param studentId the value for aiedu_student.student_id
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_student.name
     *
     * @return the value of aiedu_student.name
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_student.name
     *
     * @param name the value for aiedu_student.name
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_student.gender
     *
     * @return the value of aiedu_student.gender
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_student.gender
     *
     * @param gender the value for aiedu_student.gender
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_student.created_at
     *
     * @return the value of aiedu_student.created_at
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_student.created_at
     *
     * @param createdAt the value for aiedu_student.created_at
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_student.updated_at
     *
     * @return the value of aiedu_student.updated_at
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_student.updated_at
     *
     * @param updatedAt the value for aiedu_student.updated_at
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_student.remark
     *
     * @return the value of aiedu_student.remark
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_student.remark
     *
     * @param remark the value for aiedu_student.remark
     *
     * @mbg.generated Tue Jan 13 10:38:59 GMT+08:00 2026
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}
