package com.braight.dc.admin.web.entity;

import lombok.Data;
import org.springframework.data.annotation.Transient;

import java.sql.Date;

@Data
public class AieduLiteracyClassPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.id
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.lesson_code
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String lessonCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.title
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.title_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String titleEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.grade
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.lesson_type
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String lessonType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.lesson_type_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String lessonTypeEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.literacy
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String literacy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.literacy_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String literacyEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.unit
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.summary
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.summary_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String summaryEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.key_concepts
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String keyConcepts;
    @Transient
    private String[] keyConceptList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.key_concepts_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String keyConceptsEn;
    @Transient
    private String[] keyConceptEnList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.topic
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.topic_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String topicEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.cover_image
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String coverImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.create_time
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.update_time
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_literacy_class.ppt_canva_code
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    private String pptCanvaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.id
     *
     * @return the value of aiedu_literacy_class.id
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.id
     *
     * @param id the value for aiedu_literacy_class.id
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.lesson_code
     *
     * @return the value of aiedu_literacy_class.lesson_code
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getLessonCode() {
        return lessonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.lesson_code
     *
     * @param lessonCode the value for aiedu_literacy_class.lesson_code
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setLessonCode(String lessonCode) {
        this.lessonCode = lessonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.title
     *
     * @return the value of aiedu_literacy_class.title
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.title
     *
     * @param title the value for aiedu_literacy_class.title
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.title_en
     *
     * @return the value of aiedu_literacy_class.title_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getTitleEn() {
        return titleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.title_en
     *
     * @param titleEn the value for aiedu_literacy_class.title_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setTitleEn(String titleEn) {
        this.titleEn = titleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.grade
     *
     * @return the value of aiedu_literacy_class.grade
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.grade
     *
     * @param grade the value for aiedu_literacy_class.grade
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.lesson_type
     *
     * @return the value of aiedu_literacy_class.lesson_type
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getLessonType() {
        return lessonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.lesson_type
     *
     * @param lessonType the value for aiedu_literacy_class.lesson_type
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setLessonType(String lessonType) {
        this.lessonType = lessonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.lesson_type_en
     *
     * @return the value of aiedu_literacy_class.lesson_type_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getLessonTypeEn() {
        return lessonTypeEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.lesson_type_en
     *
     * @param lessonTypeEn the value for aiedu_literacy_class.lesson_type_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setLessonTypeEn(String lessonTypeEn) {
        this.lessonTypeEn = lessonTypeEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.literacy
     *
     * @return the value of aiedu_literacy_class.literacy
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getLiteracy() {
        return literacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.literacy
     *
     * @param literacy the value for aiedu_literacy_class.literacy
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setLiteracy(String literacy) {
        this.literacy = literacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.literacy_en
     *
     * @return the value of aiedu_literacy_class.literacy_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getLiteracyEn() {
        return literacyEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.literacy_en
     *
     * @param literacyEn the value for aiedu_literacy_class.literacy_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setLiteracyEn(String literacyEn) {
        this.literacyEn = literacyEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.unit
     *
     * @return the value of aiedu_literacy_class.unit
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.unit
     *
     * @param unit the value for aiedu_literacy_class.unit
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.summary
     *
     * @return the value of aiedu_literacy_class.summary
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.summary
     *
     * @param summary the value for aiedu_literacy_class.summary
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.summary_en
     *
     * @return the value of aiedu_literacy_class.summary_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getSummaryEn() {
        return summaryEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.summary_en
     *
     * @param summaryEn the value for aiedu_literacy_class.summary_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setSummaryEn(String summaryEn) {
        this.summaryEn = summaryEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.key_concepts
     *
     * @return the value of aiedu_literacy_class.key_concepts
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getKeyConcepts() {
        return keyConcepts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.key_concepts
     *
     * @param keyConcepts the value for aiedu_literacy_class.key_concepts
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setKeyConcepts(String keyConcepts) {
        this.keyConcepts = keyConcepts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.key_concepts_en
     *
     * @return the value of aiedu_literacy_class.key_concepts_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getKeyConceptsEn() {
        return keyConceptsEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.key_concepts_en
     *
     * @param keyConceptsEn the value for aiedu_literacy_class.key_concepts_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setKeyConceptsEn(String keyConceptsEn) {
        this.keyConceptsEn = keyConceptsEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.topic
     *
     * @return the value of aiedu_literacy_class.topic
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.topic
     *
     * @param topic the value for aiedu_literacy_class.topic
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.topic_en
     *
     * @return the value of aiedu_literacy_class.topic_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getTopicEn() {
        return topicEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.topic_en
     *
     * @param topicEn the value for aiedu_literacy_class.topic_en
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setTopicEn(String topicEn) {
        this.topicEn = topicEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.cover_image
     *
     * @return the value of aiedu_literacy_class.cover_image
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.cover_image
     *
     * @param coverImage the value for aiedu_literacy_class.cover_image
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.create_time
     *
     * @return the value of aiedu_literacy_class.create_time
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.create_time
     *
     * @param createTime the value for aiedu_literacy_class.create_time
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.update_time
     *
     * @return the value of aiedu_literacy_class.update_time
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.update_time
     *
     * @param updateTime the value for aiedu_literacy_class.update_time
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_literacy_class.ppt_canva_code
     *
     * @return the value of aiedu_literacy_class.ppt_canva_code
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public String getPptCanvaCode() {
        return pptCanvaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_literacy_class.ppt_canva_code
     *
     * @param pptCanvaCode the value for aiedu_literacy_class.ppt_canva_code
     *
     * @mbg.generated Thu Dec 25 10:12:25 GMT+08:00 2025
     */
    public void setPptCanvaCode(String pptCanvaCode) {
        this.pptCanvaCode = pptCanvaCode;
    }
}
