package com.braight.dc.admin.web.entity;

import lombok.Data;

import java.util.Date;

@Data
public class AieduTeachersPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_teachers.teacher_id
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_teachers.name
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_teachers.school
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_teachers.email
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    private String email;
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_teachers.avatar
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    private String avatar;
    private String department;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_teachers.user_id
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_teachers.created_at
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_teachers.updated_at
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_teachers.teacher_id
     *
     * @return the value of aiedu_teachers.teacher_id
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_teachers.teacher_id
     *
     * @param teacherId the value for aiedu_teachers.teacher_id
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_teachers.name
     *
     * @return the value of aiedu_teachers.name
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_teachers.name
     *
     * @param name the value for aiedu_teachers.name
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_teachers.school
     *
     * @return the value of aiedu_teachers.school
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_teachers.school
     *
     * @param school the value for aiedu_teachers.school
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_teachers.email
     *
     * @return the value of aiedu_teachers.email
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_teachers.email
     *
     * @param email the value for aiedu_teachers.email
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_teachers.avatar
     *
     * @return the value of aiedu_teachers.avatar
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_teachers.avatar
     *
     * @param avatar the value for aiedu_teachers.avatar
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_teachers.user_id
     *
     * @return the value of aiedu_teachers.user_id
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_teachers.user_id
     *
     * @param userId the value for aiedu_teachers.user_id
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_teachers.created_at
     *
     * @return the value of aiedu_teachers.created_at
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_teachers.created_at
     *
     * @param createdAt the value for aiedu_teachers.created_at
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_teachers.updated_at
     *
     * @return the value of aiedu_teachers.updated_at
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_teachers.updated_at
     *
     * @param updatedAt the value for aiedu_teachers.updated_at
     *
     * @mbg.generated Mon Jan 12 16:39:10 GMT+08:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}
