package com.braight.dc.admin.web.entity;

import lombok.Data;
import org.springframework.data.annotation.Transient;

@Data
public class AieduInquiryPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.id
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.role
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.name
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.email
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.phone
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.message
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.school_name
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.position
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.school_size
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String schoolSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String interestsJson;
    @Transient
    private String[] interests;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.subject
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.grade
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.teacher_interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String teacherInterestsJson;
    @Transient
    private String[] teacherInterests;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.child_grade
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String childGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.learning_goal
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String learningGoal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_inquiry.parent_interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    private String parentInterestsJson;
    @Transient
    private String[] parentInterests;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.id
     *
     * @return the value of aiedu_inquiry.id
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.id
     *
     * @param id the value for aiedu_inquiry.id
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.role
     *
     * @return the value of aiedu_inquiry.role
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.role
     *
     * @param role the value for aiedu_inquiry.role
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.name
     *
     * @return the value of aiedu_inquiry.name
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.name
     *
     * @param name the value for aiedu_inquiry.name
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.email
     *
     * @return the value of aiedu_inquiry.email
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.email
     *
     * @param email the value for aiedu_inquiry.email
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.phone
     *
     * @return the value of aiedu_inquiry.phone
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.phone
     *
     * @param phone the value for aiedu_inquiry.phone
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.message
     *
     * @return the value of aiedu_inquiry.message
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.message
     *
     * @param message the value for aiedu_inquiry.message
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.school_name
     *
     * @return the value of aiedu_inquiry.school_name
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.school_name
     *
     * @param schoolName the value for aiedu_inquiry.school_name
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.position
     *
     * @return the value of aiedu_inquiry.position
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.position
     *
     * @param position the value for aiedu_inquiry.position
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.school_size
     *
     * @return the value of aiedu_inquiry.school_size
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getSchoolSize() {
        return schoolSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.school_size
     *
     * @param schoolSize the value for aiedu_inquiry.school_size
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setSchoolSize(String schoolSize) {
        this.schoolSize = schoolSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.interests_json
     *
     * @return the value of aiedu_inquiry.interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getInterestsJson() {
        return interestsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.interests_json
     *
     * @param interestsJson the value for aiedu_inquiry.interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setInterestsJson(String interestsJson) {
        this.interestsJson = interestsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.subject
     *
     * @return the value of aiedu_inquiry.subject
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.subject
     *
     * @param subject the value for aiedu_inquiry.subject
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.grade
     *
     * @return the value of aiedu_inquiry.grade
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.grade
     *
     * @param grade the value for aiedu_inquiry.grade
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.teacher_interests_json
     *
     * @return the value of aiedu_inquiry.teacher_interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getTeacherInterestsJson() {
        return teacherInterestsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.teacher_interests_json
     *
     * @param teacherInterestsJson the value for aiedu_inquiry.teacher_interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setTeacherInterestsJson(String teacherInterestsJson) {
        this.teacherInterestsJson = teacherInterestsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.child_grade
     *
     * @return the value of aiedu_inquiry.child_grade
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getChildGrade() {
        return childGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.child_grade
     *
     * @param childGrade the value for aiedu_inquiry.child_grade
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setChildGrade(String childGrade) {
        this.childGrade = childGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.learning_goal
     *
     * @return the value of aiedu_inquiry.learning_goal
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getLearningGoal() {
        return learningGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.learning_goal
     *
     * @param learningGoal the value for aiedu_inquiry.learning_goal
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setLearningGoal(String learningGoal) {
        this.learningGoal = learningGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_inquiry.parent_interests_json
     *
     * @return the value of aiedu_inquiry.parent_interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public String getParentInterestsJson() {
        return parentInterestsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_inquiry.parent_interests_json
     *
     * @param parentInterestsJson the value for aiedu_inquiry.parent_interests_json
     *
     * @mbg.generated Tue Dec 30 17:59:08 GMT+08:00 2025
     */
    public void setParentInterestsJson(String parentInterestsJson) {
        this.parentInterestsJson = parentInterestsJson;
    }

}
