package com.braight.dc.admin.web.entity;

import com.alibaba.fastjson2.JSONObject;
import lombok.Data;
import org.springframework.data.annotation.Transient;

@Data
public class AieduSolutionPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.tid
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.id
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.bg_color
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String bgColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.text_color
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String textColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.title
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.title_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String titleEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.title_desktop
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String titleDesktop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.title_desktop_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String titleDesktopEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.title_mobile
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String titleMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.title_mobile_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String titleMobileEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.features
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String features;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.features_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String featuresEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.image
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.icon
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aiedu_solution.content_json
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    private String contentJson;
    @Transient
    private JSONObject solutionDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.tid
     *
     * @return the value of aiedu_solution.tid
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.tid
     *
     * @param tid the value for aiedu_solution.tid
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.id
     *
     * @return the value of aiedu_solution.id
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.id
     *
     * @param id the value for aiedu_solution.id
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.bg_color
     *
     * @return the value of aiedu_solution.bg_color
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getBgColor() {
        return bgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.bg_color
     *
     * @param bgColor the value for aiedu_solution.bg_color
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setBgColor(String bgColor) {
        this.bgColor = bgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.text_color
     *
     * @return the value of aiedu_solution.text_color
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getTextColor() {
        return textColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.text_color
     *
     * @param textColor the value for aiedu_solution.text_color
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setTextColor(String textColor) {
        this.textColor = textColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.title
     *
     * @return the value of aiedu_solution.title
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.title
     *
     * @param title the value for aiedu_solution.title
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.title_en
     *
     * @return the value of aiedu_solution.title_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getTitleEn() {
        return titleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.title_en
     *
     * @param titleEn the value for aiedu_solution.title_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setTitleEn(String titleEn) {
        this.titleEn = titleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.title_desktop
     *
     * @return the value of aiedu_solution.title_desktop
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getTitleDesktop() {
        return titleDesktop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.title_desktop
     *
     * @param titleDesktop the value for aiedu_solution.title_desktop
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setTitleDesktop(String titleDesktop) {
        this.titleDesktop = titleDesktop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.title_desktop_en
     *
     * @return the value of aiedu_solution.title_desktop_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getTitleDesktopEn() {
        return titleDesktopEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.title_desktop_en
     *
     * @param titleDesktopEn the value for aiedu_solution.title_desktop_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setTitleDesktopEn(String titleDesktopEn) {
        this.titleDesktopEn = titleDesktopEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.title_mobile
     *
     * @return the value of aiedu_solution.title_mobile
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getTitleMobile() {
        return titleMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.title_mobile
     *
     * @param titleMobile the value for aiedu_solution.title_mobile
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setTitleMobile(String titleMobile) {
        this.titleMobile = titleMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.title_mobile_en
     *
     * @return the value of aiedu_solution.title_mobile_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getTitleMobileEn() {
        return titleMobileEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.title_mobile_en
     *
     * @param titleMobileEn the value for aiedu_solution.title_mobile_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setTitleMobileEn(String titleMobileEn) {
        this.titleMobileEn = titleMobileEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.features
     *
     * @return the value of aiedu_solution.features
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getFeatures() {
        return features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.features
     *
     * @param features the value for aiedu_solution.features
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setFeatures(String features) {
        this.features = features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.features_en
     *
     * @return the value of aiedu_solution.features_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getFeaturesEn() {
        return featuresEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.features_en
     *
     * @param featuresEn the value for aiedu_solution.features_en
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setFeaturesEn(String featuresEn) {
        this.featuresEn = featuresEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.image
     *
     * @return the value of aiedu_solution.image
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.image
     *
     * @param image the value for aiedu_solution.image
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.icon
     *
     * @return the value of aiedu_solution.icon
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.icon
     *
     * @param icon the value for aiedu_solution.icon
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aiedu_solution.content_json
     *
     * @return the value of aiedu_solution.content_json
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public String getContentJson() {
        return contentJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aiedu_solution.content_json
     *
     * @param contentJson the value for aiedu_solution.content_json
     *
     * @mbg.generated Mon Dec 29 17:37:05 GMT+08:00 2025
     */
    public void setContentJson(String contentJson) {
        this.contentJson = contentJson;
    }
}
